### ISSUE TITLE
Error while running the jar.

### ISSUE THREAD

**Issue by InfiniteCod3** [AlexProgrammerDE/ServerWrecker#105]
java -jar serverwrecker-all.jar
SLF4J: A SLF4J service provider failed to instantiate:
org.slf4j.spi.SLF4JServiceProvider: Provider ch.qos.logback.classic.spi.LogbackServiceProvider not found
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
java.lang.ClassCastException: class org.slf4j.helpers.NOPLogger cannot be cast to class ch.qos.logback.classic.Logger (org.slf4j.helpers.NOPLogger and ch.qos.logback.classic.Logger are in unnamed module of loader 'app')
        at net.pistonmaster.serverwrecker.logging.LogUtil.setLevel(LogUtil.java:32)
        at net.pistonmaster.serverwrecker.logging.LogUtil.setLevel(LogUtil.java:28)
        at net.pistonmaster.serverwrecker.ServerWrecker.setupLogging(ServerWrecker.java:359)
        at net.pistonmaster.serverwrecker.ServerWrecker.<init>(ServerWrecker.java:103)
        at net.pistonmaster.serverwrecker.CommandDefinition.call(CommandDefinition.java:103)
        at net.pistonmaster.serverwrecker.CommandDefinition.call(CommandDefinition.java:32)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at net.pistonmaster.serverwrecker.Main.runHeadless(Main.java:61)
        at net.pistonmaster.serverwrecker.Main.main(Main.java:42)
        
        
        
        that is the error i got

**Comment by AlexProgrammerDE** [comment]
Alright thanks for the report. I will be looking into this soon. Already was able to reproduce it.

**Comment by AlexProgrammerDE** [comment]
Fixed by https://github.com/AlexProgrammerDE/ServerWrecker/commit/f3cf3a3c720a7a36a89ca64431dcd3db95c3cb95
Thanks for the report! You can now download the latest version from nightly.link

**Comment by InfiniteCod3** [comment]
> Fixed by [f3cf3a3](https://github.com/AlexProgrammerDE/ServerWrecker/commit/f3cf3a3c720a7a36a89ca64431dcd3db95c3cb95) Thanks for the report! You can now download the latest version from nightly.link



Artifact 'ServerWrecker' not found for run #4809354688.

**Comment by AlexProgrammerDE** [comment]
Alright try again

**Comment by InfiniteCod3** [comment]
also compiled it myself still broken:

java -jar serverwrecker-all.jar
java.lang.NullPointerException
        at java.base/java.io.Reader.<init>(Reader.java:168)
        at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:76)
        at net.pistonmaster.serverwrecker.ServerWrecker.<init>(ServerWrecker.java:117)
        at net.pistonmaster.serverwrecker.CommandDefinition.call(CommandDefinition.java:103)
        at net.pistonmaster.serverwrecker.CommandDefinition.call(CommandDefinition.java:32)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at net.pistonmaster.serverwrecker.Main.runHeadless(Main.java:61)
        at net.pistonmaster.serverwrecker.Main.main(Main.java:42)

**Comment by InfiniteCod3** [comment]
i tried the compiled version outputs the same error

**Comment by AlexProgrammerDE** [comment]
Alright so this is a brand new issue. I'm investigating.

**Comment by InfiniteCod3** [comment]
java.lang.NullPointerException: en_us.json not found
        at java.base/java.util.Objects.requireNonNull(Objects.java:233)
        at net.pistonmaster.serverwrecker.ServerWrecker.<init>(ServerWrecker.java:116)
        at net.pistonmaster.serverwrecker.CommandDefinition.call(CommandDefinition.java:103)
        at net.pistonmaster.serverwrecker.CommandDefinition.call(CommandDefinition.java:32)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at net.pistonmaster.serverwrecker.Main.runHeadless(Main.java:61)
        at net.pistonmaster.serverwrecker.Main.main(Main.java:42)

**Comment by AlexProgrammerDE** [comment]
Hm that's very weird. I cannot reproduce this issue. What Java version are you using? (`java -version`) and are you using the latest version from nightly.link?

**Comment by InfiniteCod3** [comment]
openjdk version "18.0.2-ea" 2022-07-19
OpenJDK Runtime Environment (build 18.0.2-ea+9-Ubuntu-2ubuntu1)
OpenJDK 64-Bit Server VM (build 18.0.2-ea+9-Ubuntu-2ubuntu1, mixed mode, sharing)

yes I'm on the latest version

**Comment by InfiniteCod3** [comment]
Its probably because i dont have the locales for it, ill see if i can install them and if that fixes it

**Comment by AlexProgrammerDE** [comment]
The locales should be inside the jar, which is weird.

**Comment by AlexProgrammerDE** [comment]
![image](https://user-images.githubusercontent.com/40795980/234614675-d5530e18-cf8b-4f9e-9526-82f075428b7f.png)
Oh it seems like the nightly build doesn't include the file. My local builds include it. I'm investigating that now.

**Comment by InfiniteCod3** [comment]
oh, alright

**Comment by AlexProgrammerDE** [comment]
Alright file issue is fixed now as well!

**Comment by InfiniteCod3** [comment]
loads fine now :)
